[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    'safe-contracts/=lib/safe-contracts/contracts/',
    'solmate/=lib/solmate/src/'
]

[rpc_endpoints]
mainnet = "${RPC_MAINNET}" 

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }